In [5]:
import numpy as np
import time
import sys
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
l = range(1000)
print(sys.getsizeof(5)*len(l))
array = np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [19]:
SIZE = 100000
l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# python list
start = time.time()
result = [(x + y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time() - start)*1000) #here *1000 for ms conversion
# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start)*1000) #here *1000 for ms conversion

python list took:  7.7991485595703125
numpy took:  1.2965202331542969


In [21]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1 + a2)
print(a1 - a2)
print(a1 / a2)
print(a1 * a2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [26]:
a = np.array([5,6,9])
a = np.array([1,2,3])
print(a[0])
print(a[1])
print(a[2])

1
2
3


In [34]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
a = np.array([[1,2], [3,4], [5,6]], dtype=np.int32)
print(a)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
a = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
print(a)
print(a.ndim)
print(a.itemsize)
print(a.dtype)

[[1 2]
 [3 4]
 [5 6]]
2
8
int64
[[1 2]
 [3 4]
 [5 6]]
2
4
int32
[[1. 2.]
 [3. 4.]
 [5. 6.]]
2
8
float64


In [37]:
print(a.size)
print(a.shape)
a = np.array([[1,2], [3,4], [5,6]], dtype=np.complex)
print(a)

6
(3, 2)
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [40]:
print("Zeros array")
print(np.zeros((3,4)))
print("Ones array")
print(np.ones((3,4)))

Zeros array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
print(np.arange(1,5))
print(np.arange(1,5,2)) # 3rd param is step
print(np.linspace(1,5,10)) #3rd param is numbers between start and stop you want to generate
print(np.linspace(1,5,20))

[1 2 3 4]
[1 3]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [64]:
a = np.array([[1,2], [3,4], [5,6]])
print("original array")
print(a)
print("original array shape")
print(a.shape)
a = a.reshape(2,3) #Here it is imp to return result into a omly then modification works...i.e a.reshape(2,3) will not work but a = a.reshape(2,3) will work
print("modified array")
print(a)
print("modified array shape")
print(a.shape)
a = a.reshape(6,1)
print("modified array")
print(a)
print("modified array shape")
print(a.shape)

original array
[[1 2]
 [3 4]
 [5 6]]
original array shape
(3, 2)
modified array
[[1 2 3]
 [4 5 6]]
modified array shape
(2, 3)
modified array
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
modified array shape
(6, 1)


In [62]:
a = a.ravel() # flatten array into one dimensional array
a

array([1, 2, 3, 4, 5, 6])

In [65]:
print(a.min())
print(a.max())
print(a.sum())

1
6
21


In [68]:
a = a.reshape(3,2)
print(a.sum(axis=0)) # coloum wise addition
print(a.sum(axis=1)) # row wise addition

[ 9 12]
[ 3  7 11]


In [69]:
np.sqrt(a) #calculate square root of array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [70]:
np.std(a) #calculate standard deviation

1.707825127659933

In [184]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print("a")
print(a)
print("b")
print(b)
print("a + b")
print(a+b)
print("a - b")
print(a-b)
print("a * b")
print(a*b)
print("a / b")
print(a/b)
print("matrix product")
print(a.dot(b))
print("matrix product again")
print(a@b)

a
[[1 2]
 [3 4]]
b
[[5 6]
 [7 8]]
a + b
[[ 6  8]
 [10 12]]
a - b
[[-4 -4]
 [-4 -4]]
a * b
[[ 5 12]
 [21 32]]
a / b
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
matrix product
[[19 22]
 [43 50]]
matrix product again
[[19 22]
 [43 50]]


In [83]:
# numpy Indexing and slicing
a = np.array([6,7,8])
print(a[0:2])
print(a[-1])

[6 7]
8
[[6 7 8]
 [1 2 3]
 [9 3 2]]


In [91]:
a= np.array([[6,7,8], [1,2,3], [9,3,2]])
print(a)
print(a[1,2])
print(a[0:2,2]) #prints 2nd index coloum from 0th and 1th index rows
print(a[-1]) #prints last row
print(a[-1, 0:2]) #prints last row 0th and 1th index coloumns
print(a[:, 1:3]) #goes through all rows printing 1st and 2nd index coloumns

[[6 7 8]
 [1 2 3]
 [9 3 2]]
3
[8 3]
[9 3 2]
[9 3]
[[7 8]
 [2 3]
 [3 2]]


In [92]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [93]:
for cell in a.flat: #a.flat flattens the array into one-dimensional array
    print(cell)

6
7
8
1
2
3
9
3
2


In [207]:
a = np.arange(0,6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [209]:
print(np.vstack((a,b))) #vertically stacks both arrays into one another similar to np.row_stack(a,b)
print(np.row_stack((a,b)))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [211]:
print(np.hstack((a,b))) #horizontal stacks both arrays with one another similar to column_stack(a,b)
print(np.column_stack((a,b)))

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [101]:
a = np.arange(30).reshape(2,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [115]:
result = np.hsplit(a,3) #horizontal split array into 3 parts
print("result")
print(result)
print("result[o]")
print(result[0])
print("result[1]")
print(result[1])
print("result[2]")
print(result[2])

result
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
result[o]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
result[1]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
result[2]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [117]:
result = np.vsplit(a,2) #vertical split array into 3 parts
print("result")
print(result)
print("result[o]")
print(result[0])
print("result[1]")
print(result[1])

result
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]
result[o]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
result[1]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [120]:
a = np.arange(12).reshape(3,4)
print(a)
b = a > 4
print("b array")
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b array
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [122]:
# Way of extracting all elements of array which are gretaer than 4 as specified in condition
a[b] #prints every element of a array which has mapped True value in b array.

array([ 5,  6,  7,  8,  9, 10, 11])

In [124]:
a[b] = -1 #replace all the numbers >4 with -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [126]:
a = np.arange(12).reshape(3,4)
for cell in a.flatten(): #flattens list in one dimensional array
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [127]:
for x in np.nditer(a,order="C"): #C-Order
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [128]:
for x in np.nditer(a,order="F"): #Fortan-Order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [129]:
for x in np.nditer(a,order="F",flags=["external_loop"]): #flag=external_loop prints entire coloum in F order specified
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [165]:
for x in np.nditer(a,op_flags=["readwrite"]): #read documentation for more details
    x[...]=x*x

In [166]:
a

array([[                   0,           1073741824,                    0,
         7107135960634097664],
       [                   0,  5450850336250003456,                    0,
        -4109892000180862976],
       [                   0, -4482140457857449984,                    0,
         5390568511745556480]])

In [167]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [173]:
'''BroadCasting Rules
When Operating on two arrays, Numpy compares their shapes element-wise.It starts with trailing-dimensions and works its way forward.
Two dimennsions are compatible when
1. they are  equal, or
2. one of them is 1
'''

for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1073741824 3
0 3
7107135960634097664 3
0 7
5450850336250003456 7
0 7
-4109892000180862976 7
0 11
-4482140457857449984 11
0 11
5390568511745556480 11


In [279]:
a = np.arange(0,12).reshape(3,4)
a = a.T # Transpose of array
print(a)
a = a.transpose() # Transpose of array
print(a)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [186]:
a.resize((2,6)) #here original array itself is modified alternative to reshape() where original array is not modified but returns new modified array
a

array([[1, 2, 3, 4, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [193]:
a.reshape(3,-1) #here -1 argument indictaes that this dimension will be calculated automatically
a

array([[1, 2, 3, 4, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [214]:
# No copy of array objects
a = np.arange(12)
b = a #a and b are two names for same ndarray object
print(b is a)
b.shape = 3,4
print(a.shape)


def f(x):
    print(id(x))

print(id(a))
f(a)

True
(3, 4)
140557071323504
140557071323504


In [221]:
# View or shallow copy
c = a.view() # view method creates a new array object that looks at same data
print(c is a)
print(c.base is a) #c is a view of the data owned by a
print(c.flags.owndata) #checks whether c owns data itself
c.shape = 2,6
print(a.shape) #a's shape doesn't change
print(a)
c[0,4] = 1234
print(a) #a's data changes

s = a[:,1:3]
s[:] = 10
print(a)

False
True
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [225]:
# Deep Copy
d = a.copy() # a new array object with new data is created
print(d is a)
print(d.base is a)
d[0,0] = 9999
print(a) # a's data does'nt changes

False
False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [229]:
a = np.arange(12)**2
print(a)
i = np.array([1,1,3,8,5])
print(a[i]) #the elements of a at the position i
j = np.array([[3,4], [9,7]])
print(a[j]) #the elements of a at the position j having same shape as j

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [234]:
time = np.linspace(20,145,5)
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
ind = data.argmax(axis=0) #find index of max element coloumn wise
print(ind)
time_max = time[ind]  #times corresponding to maxima
print(time_max)
data_max = data[ind, range(data.shape[1])] # => data[ind[0],0], data[ind[1],1] ...
print(data_max)
np.all(data_max == data.max(axis=0))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 82.5   20.   113.75  51.25]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


True

In [251]:
# ix_() function
#use case for 3D array
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c)
print(ax) #it is 1st dimension choosing uppermost specified index matrix from parent matrix
print(bx) #it is 2nd dimension choosing specified index rows from choosen matrix
print(cx) #it is 3rd dimension choosing specified index coloumn from choosen matrix
print(ax.shape, bx.shape, cx.shape)
result = ax+bx*cx
print(result)
print(result[3,2,4])
print(a[3] + b[2] * c[4])

[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[[8]
  [5]
  [4]]]
[[[5 4 6 8 3]]]
(4, 1, 1) (1, 3, 1) (1, 1, 5)
[[[42 34 50 66 26]
  [27 22 32 42 17]
  [22 18 26 34 14]]

 [[43 35 51 67 27]
  [28 23 33 43 18]
  [23 19 27 35 15]]

 [[44 36 52 68 28]
  [29 24 34 44 19]
  [24 20 28 36 16]]

 [[45 37 53 69 29]
  [30 25 35 45 20]
  [25 21 29 37 17]]]
17
17


In [236]:
 # indexing within arrays as a target to assign to
    a= np.arange(5)
    a[[0,0,2]] = [1,2,3] #repetitive indexing within array could cause repetitive updations with last updated value
    print(a)
    a[[0,0,2]] += 1 # this syntax prevents repetitive indexing within array to cause repetitive updations
    print(a)

[2 1 3 3 4]
[3 1 4 3 4]


In [265]:
a = np.array([[1,2], [3,4]])
r1 = np.sum(a, axis=1)

In [263]:
r1
b = r1 > 4
print(b)
a[b]

[False  True]


array([[3, 4]])

In [269]:
a = np.arange(10).reshape(2,5)
print(a)
ixgrid = np.ix_([0,1],[2,4])
print(ixgrid) #indicating 0th and 1st index row along with 2nd and 4th index coloumn
print(a[ixgrid]) #printing values from a array mapped to 0th and 1st array selecting 2nd and 4th coloumn elements

ixgrid = np.ix_([True,True],[2,4])
print(a[ixgrid])

ixgrid = np.ix_([True,True],[False,False,True,False,True])
print(a[ixgrid])

[[0 1 2 3 4]
 [5 6 7 8 9]]
(array([[0],
       [1]]), array([[2, 4]]))
[[2 4]
 [7 9]]
[[2 4]
 [7 9]]
[[2 4]
 [7 9]]


In [283]:
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a)) #inverse of matrix
print(np.eye(2)) #eye matrix of 2*2
print(np.trace(a)) #trace of a

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
5


In [284]:
#Automatic Reshaping
# To change dimensions of array, you can omit one of sizes which will then be deduced automatically
a = np.arange(30)
a.shape = 2,-1,3 #-1 means "whatever is needed"
a.shape

(2, 5, 3)

In [286]:
np.tile(2,(5,2)) #1st param indicates value to be filled in matrix and 2nd param indicates shape of matrix

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [287]:
np.tile(np.arange(10), (5,3))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9]])

In [288]:
np.repeat([1,2],5) #takes each element from ist and repeat it as specified in 2nd param

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [290]:
#Structured Array
x =np.array([("a", 0.8), ("b", 0.2)], dtype=[("label", "a8"), ("prob", "f8")])
print(x)
print(x["label"])
print(x["prob"])

[(b'a', 0.8) (b'b', 0.2)]
[b'a' b'b']
[0.8 0.2]


In [291]:
a = np.arange(25)
a[:, np.newaxis] #newaxis is used to print element in new axis

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [6]:
a = np.arange(25).reshape(5,5,1)
print(a)
a[1,...] # ... i.e ellipses defines take every dimension after any specified dimension. here it means take 1st row and everything after that.

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]
  [24]]]


array([[5],
       [6],
       [7],
       [8],
       [9]])

In [15]:
a = np.ones((5,5,1))
print(a.shape)
a = a.squeeze()
print(a.shape)
a = a[:,:,np.newaxis]
print(a.shape)

(5, 5, 1)
(5, 5)
(5, 5, 1)
